stages:
 - staging
 - production
 
staging:
  stage: staging
  tags:
  - ansible
  script:
  - npm start
  only:
  - tags

production:
  stage: production
  tags:
  - ansible
  script:
  - npm install --save @angular-devkit/build-angular
  - npm link
  - ng build --prod --aot --output-hashing=none
  only:
  - tags