var listCurrency = [   
    ['USD', 'United States Dollar (USD)'],
    ['EUR', 'Euro (EUR)'],
    ['CNY', 'Chinese Renminbi Yuan (CNY)'],
    ['GBP', 'British Pound (GBP)'],
    ['CAD', 'Canadian Dollar (CAD)'],
    ['---', '---', true],
    ['AFN', 'Afghan Afghani (AFN)'],
    ['ALL', 'Albanian Lek (ALL)'],
    ['DZD', 'Algerian Dinar (DZD)'],
    ['ARS', 'Argentine Peso (ARS)'],
    ['AMD', 'Armenian Dram (AMD)'],
    ['AWG', 'Aruban Florin (AWG)'],
    ['AOA', 'Aurora (AOA)'],
    ['AUD', 'Australian Dollar (AUD)'],
    ['AZN', 'Azerbaijani Manat (AZN)'],
    ['BSD', 'Bahamian Dollar (BSD)'],
    ['BHD', 'Bahraini Dinar (BHD)'],
    ['BDT', 'Bangladeshi Taka (BDT)'],
    ['BBD', 'Barbadian Dollar (BBD)'],
    ['BYN', 'Belarusian Ruble (BYN)'],
    ['BYR', 'Belarusian Ruble (BYR)'],
    ['BZD', 'Belize Dollar (BZD)'],
    ['BMD', 'Bermudian Dollar (BMD)'],
    ['BTN', 'Bhutanese Ngultrum (BTN)'],
    ['BOB', 'Bolivian Boliviano (BOB)'],
    ['BAM', 'Bosnia and Herzegovina Convertible Mark (BAM)'],
    ['BWP', 'Botswana Pula (BWP)'],
    ['BRL', 'Brazilian Real (BRL)'],
    ['BND', 'Brunei Dollar (BND)'],
    ['BGN', 'Bulgarian Lev (BGN)'],
    ['BIF', 'Burundian Franc (BIF)'],
    ['KHR', 'Cambodian Riel (KHR)'],
    ['CVE', 'Cape Verdean Escudo (CVE)'],
    ['KYD', 'Cayman Islands Dollar (KYD)'],
    ['XAF', 'Central African Cfa Franc (XAF)'],
    ['XPF', 'Cfp Franc (XPF)'],
    ['CLP', 'Chilean Peso (CLP)'],
    ['CNH', 'Chinese Renminbi Yuan Offshore (CNH)'],
    ['COP', 'Colombian Peso (COP)'],
    ['KMF', 'Comorian Franc (KMF)'],
    ['CDF', 'Congolese Franc (CDF)'],
    ['CRC', 'Costa Rican Colón (CRC)'],
    ['HRK', 'Croatian Kuna (HRK)'],
    ['CUC', 'Cuban Convertible Peso (CUC)'],
    ['CZK', 'Czech Koruna (CZK)'],
    ['DKK', 'Danish Krone (DKK)'],
    ['DJF', 'Djiboutian Franc (DJF)'],
    ['DOP', 'Dominican Peso (DOP)'],
    ['XCD', 'East Caribbean Dollar (XCD)'],
    ['EGP', 'Egyptian Pound (EGP)'],
    ['ERN', 'Eritrean Nakfa (ERN)'],
    ['EEK', 'Estonian Kroon (EEK)'],
    ['ETB', 'Ethiopian Birr (ETB)'],
    ['FKP', 'Falkland Pound (FKP)'],
    ['FJD', 'Fijian Dollar (FJD)'],
    ['GMD', 'Gambian Dalasi (GMD)'],
    ['GEL', 'Georgian Lari (GEL)'],
    ['GHS', 'Ghanaian Cedi (GHS)'],
    ['GIP', 'Gibraltar Pound (GIP)'],
    ['XAU', 'Gold (Troy Ounce) (XAU)'],
    ['GTQ', 'Guatemalan Quetzal (GTQ)'],
    ['GGP', 'Guernsey Pound (GGP)'],
    ['GNF', 'Guinean Franc (GNF)'],
    ['GYD', 'Guyanese Dollar (GYD)'],
    ['HTG', 'Haitian Gourde (HTG)'],
    ['HNL', 'Honduran Lempira (HNL)'],
    ['HKD', 'Hong Kong Dollar (HKD)'],
    ['HUF', 'Hungarian Forint (HUF)'],
    ['ISK', 'Icelandic Króna (ISK)'],
    ['INR', 'Indian Rupee (INR)'],
    ['IDR', 'Indonesian Rupiah (IDR)'],
    ['IQD', 'Iraqi Dinar (IQD)'],
    ['IMP', 'Isle of Man Pound (IMP)'],
    ['ILS', 'Israeli New Sheqel (ILS)'],
    ['JMD', 'Jamaican Dollar (JMD)'],
    ['JPY', 'Japanese Yen (JPY)'],
    ['JEP', 'Jersey Pound (JEP)'],
    ['JOD', 'Jordanian Dinar (JOD)'],
    ['KZT', 'Kazakhstani Tenge (KZT)'],
    ['KES', 'Kenyan Shilling (KES)'],
    ['KWD', 'Kuwaiti Dinar (KWD)'],
    ['KGS', 'Kyrgyzstani Som (KGS)'],
    ['LAK', 'Lao Kip (LAK)'],
    ['LVL', 'Latvian Lats (LVL)'],
    ['LBP', 'Lebanese Pound (LBP)'],
    ['LSL', 'Lesotho Loti (LSL)'],
    ['LRD', 'Liberian Dollar (LRD)'],
    ['LYD', 'Libyan Dinar (LYD)'],
    ['LTL', 'Lithuanian Litas (LTL)'],
    ['MOP', 'Macanese Pataca (MOP)'],
    ['MKD', 'Macedonian Denar (MKD)'],
    ['MGA', 'Malagasy Ariary (MGA)'],
    ['MWK', 'Malawian Kwacha (MWK)'],
    ['MYR', 'Malaysian Ringgit (MYR)'],
    ['MVR', 'Maldivian Rufiyaa (MVR)'],
    ['MTL', 'Maltese Lira (MTL)'],
    ['MRO', 'Mauritanian Ouguiya (MRO)'],
    ['MUR', 'Mauritian Rupee (MUR)'],
    ['MXN', 'Mexican Peso (MXN)'],
    ['MDL', 'Moldovan Leu (MDL)'],
    ['MNT', 'Mongolian Tögrög (MNT)'],
    ['MAD', 'Moroccan Dirham (MAD)'],
    ['MZN', 'Mozambican Metical (MZN)'],
    ['MMK', 'Myanmar Kyat (MMK)'],
    ['NAD', 'Namibian Dollar (NAD)'],
    ['NPR', 'Nepalese Rupee (NPR)'],
    ['ANG', 'Netherlands Antillean Gulden (ANG)'],
    ['TWD', 'New Taiwan Dollar (TWD)'],
    ['NZD', 'New Zealand Dollar (NZD)'],
    ['NIO', 'Nicaraguan Córdoba (NIO)'],
    ['NGN', 'Nigerian Naira (NGN)'],
    ['NOK', 'Norwegian Krone (NOK)'],
    ['OMR', 'Omani Rial (OMR)'],
    ['PKR', 'Pakistani Rupee (PKR)'],
    ['XPD', 'Palladium (XPD)'],
    ['PAB', 'Panamanian Balboa (PAB)'],
    ['PGK', 'Papua New Guinean Kina (PGK)'],
    ['PYG', 'Paraguayan Guaraní (PYG)'],
    ['PEN', 'Peruvian Sol (PEN)'],
    ['PHP', 'Philippine Peso (PHP)'],
    ['XPT', 'Platinum (XPT)'],
    ['PLN', 'Polish Z?oty (PLN)'],
    ['QAR', 'Qatari Riyal (QAR)'],
    ['RON', 'Romanian Leu (RON)'],
    ['RUB', 'Russian Ruble (RUB)'],
    ['RWF', 'Rwandan Franc (RWF)'],
    ['SHP', 'Saint Helenian Pound (SHP)'],
    ['SVC', 'Salvadoran Colón (SVC)'],
    ['WST', 'Samoan Tala (WST)'],
    ['SAR', 'Saudi Riyal (SAR)'],
    ['RSD', 'Serbian Dinar (RSD)'],
    ['SCR', 'Seychellois Rupee (SCR)'],
    ['SLL', 'Sierra Leonean Leone (SLL)'],
    ['XAG', 'Silver (Troy Ounce) (XAG)'],
    ['SGD', 'Singapore Dollar (SGD)'],
    ['SBD', 'Solomon Islands Dollar (SBD)'],
    ['SOS', 'Somali Shilling (SOS)'],
    ['ZAR', 'South African Rand (ZAR)'],
    ['KRW', 'South Korean Won (KRW)'],
    ['SSP', 'South Sudanese Pound (SSP)'],
    ['XDR', 'Special Drawing Rights (XDR)'],
    ['LKR', 'Sri Lankan Rupee (LKR)'],
    ['SRD', 'Surinamese Dollar (SRD)'],
    ['SZL', 'Swazi Lilangeni (SZL)'],
    ['SEK', 'Swedish Krona (SEK)'],
    ['CHF', 'Swiss Franc (CHF)'],
    ['STD', 'São Tomé and Príncipe Dobra (STD)'],
    ['TJS', 'Tajikistani Somoni (TJS)'],
    ['TZS', 'Tanzanian Shilling (TZS)'],
    ['THB', 'Thai Baht (THB)'],
    ['TOP', "Tongan Pa'anga (TOP)"],
    ['TTD', 'Trinidad and Tobago Dollar (TTD)'],
    ['TND', 'Tunisian Dinar (TND)'],
    ['TRY', 'Turkish Lira (TRY)'],
    ['TMT', 'Turkmenistani Manat (TMT)'],
    ['UGX', 'Ugandan Shilling (UGX)'],
    ['UAH', 'Ukrainian Hryvnia (UAH)'],
    ['CLF', 'Unidad de Fomento (CLF)'],
    ['AED', 'United Arab Emirates Dirham (AED)'],
    ['UYU', 'Uruguayan Peso (UYU)'],
    ['UZS', 'Uzbekistan Som (UZS)'],
    ['VUV', 'Vanuatu Vatu (VUV)'],
    ['VEF', 'Venezuelan Bolívar (VEF)'],
    ['VND', 'Vietnamese Ðong (VND)'],
    ['XOF', 'West African Cfa Franc (XOF)'],
    ['YER', 'Yemeni Rial (YER)'],
    ['ZMK', 'Zambian Kwacha (ZMK)'],
    ['ZMW', 'Zambian Kwacha (ZMW)'],
    ['ZWL', 'Zimbabwean Dollar (ZWL)'],
];
export class Currency {
    key: string;
    name: string;
    disabled: boolean;

    constructor(key, name, disabled = false) {
        this.key = key;
        this.name = name;
        this.disabled = disabled;
    }

    static getListCurrency(): Currency[] {
        return listCurrency.map(x => new Currency(x[0], x[1], Boolean(x[2])));
    }
}