const listTimeZone = [{
    "country":"Africa/Abidjan",
    "timeZone":"+00:00"
  },{
    "country":"Africa/Accra",
    "timeZone":"+00:00"
  },{
    "country":"Africa/Addis_Ababa",
    "timeZone":"+03:00"
  },{
    "country":"Africa/Algiers",
    "timeZone":"+01:00"
  },{
    "country":"Africa/Asmara",
    "timeZone":"+03:00"
  },{
    "country":"Africa/Bamako",
    "timeZone":"+00:00"
  },{
    "country":"Africa/Bangui",
    "timeZone":"+01:00"
  },{
    "country":"Africa/Banjul",
    "timeZone":"+00:00"
  },{
    "country":"Africa/Bissau",
    "timeZone":"+00:00"
  },{
    "country":"Africa/Blantyre",
    "timeZone":"+02:00"
  },{
    "country":"Africa/Brazzaville",
    "timeZone":"+01:00"
  },{
    "country":"Africa/Bujumbura",
    "timeZone":"+02:00"
  },{
    "country":"Africa/Cairo",
    "timeZone":"+02:00"
  },{
    "country":"Africa/Casablanca",
    "timeZone":"+01:00"
  },{
    "country":"Africa/Ceuta",
    "timeZone":"+01:00"
  },{
    "country":"Africa/Conakry",
    "timeZone":"+00:00"
  },{
    "country":"Africa/Dakar",
    "timeZone":"+00:00"
  },{
    "country":"Africa/Dar_es_Salaam",
    "timeZone":"+03:00"
  },{
    "country":"Africa/Djibouti",
    "timeZone":"+03:00"
  },{
    "country":"Africa/Douala",
    "timeZone":"+01:00"
  },{
    "country":"Africa/El_Aaiun",
    "timeZone":"+00:00"
  },{
    "country":"Africa/Freetown",
    "timeZone":"+00:00"
  },{
    "country":"Africa/Gaborone",
    "timeZone":"+02:00"
  },{
    "country":"Africa/Harare",
    "timeZone":"+02:00"
  },{
    "country":"Africa/Johannesburg",
    "timeZone":"+02:00"
  },{
    "country":"Africa/Juba",
    "timeZone":"+03:00"
  },{
    "country":"Africa/Kampala",
    "timeZone":"+03:00"
  },{
    "country":"Africa/Khartoum",
    "timeZone":"+02:00"
  },{
    "country":"Africa/Kigali",
    "timeZone":"+02:00"
  },{
    "country":"Africa/Kinshasa",
    "timeZone":"+01:00"
  },{
    "country":"Africa/Lagos",
    "timeZone":"+01:00"
  },{
    "country":"Africa/Libreville",
    "timeZone":"+01:00"
  },{
    "country":"Africa/Lome",
    "timeZone":"+00:00"
  },{
    "country":"Africa/Luanda",
    "timeZone":"+01:00"
  },{
    "country":"Africa/Lubumbashi",
    "timeZone":"+02:00"
  },{
    "country":"Africa/Lusaka",
    "timeZone":"+02:00"
  },{
    "country":"Africa/Malabo",
    "timeZone":"+01:00"
  },{
    "country":"Africa/Maputo",
    "timeZone":"+02:00"
  },{
    "country":"Africa/Maseru",
    "timeZone":"+02:00"
  },{
    "country":"Africa/Mbabane",
    "timeZone":"+02:00"
  },{
    "country":"Africa/Mogadishu",
    "timeZone":"+03:00"
  },{
    "country":"Africa/Monrovia",
    "timeZone":"+00:00"
  },{
    "country":"Africa/Nairobi",
    "timeZone":"+03:00"
  },{
    "country":"Africa/Ndjamena",
    "timeZone":"+01:00"
  },{
    "country":"Africa/Niamey",
    "timeZone":"+01:00"
  },{
    "country":"Africa/Nouakchott",
    "timeZone":"+00:00"
  },{
    "country":"Africa/Ouagadougou",
    "timeZone":"+00:00"
  },{
    "country":"Africa/Porto-Novo",
    "timeZone":"+01:00"
  },{
    "country":"Africa/Sao_Tome",
    "timeZone":"+01:00"
  },{
    "country":"Africa/Timbuktu",
    "timeZone":"+00:00"
  },{
    "country":"Africa/Tripoli",
    "timeZone":"+02:00"
  },{
    "country":"Africa/Tunis",
    "timeZone":"+01:00"
  },{
    "country":"Africa/Windhoek",
    "timeZone":"+02:00"
  },{
    "country":"America/Adak",
    "timeZone":"−10:00"
  },{
    "country":"America/Anchorage",
    "timeZone":"−09:00"
  },{
    "country":"America/Anguilla",
    "timeZone":"−04:00"
  },{
    "country":"America/Antigua",
    "timeZone":"−04:00"
  },{
    "country":"America/Araguaina",
    "timeZone":"−03:00"
  },{
    "country":"America/Argentina/Buenos_Aires",
    "timeZone":"−03:00"
  },{
    "country":"America/Argentina/Catamarca",
    "timeZone":"−03:00"
  },{
    "country":"America/Argentina/ComodRivadavia",
    "timeZone":"−03:00"
  },{
    "country":"America/Argentina/Cordoba",
    "timeZone":"−03:00"
  },{
    "country":"America/Argentina/Jujuy",
    "timeZone":"−03:00"
  },{
    "country":"America/Argentina/La_Rioja",
    "timeZone":"−03:00"
  },{
    "country":"America/Argentina/Mendoza",
    "timeZone":"−03:00"
  },{
    "country":"America/Argentina/Rio_Gallegos",
    "timeZone":"−03:00"
  },{
    "country":"America/Argentina/Salta",
    "timeZone":"−03:00"
  },{
    "country":"America/Argentina/San_Juan",
    "timeZone":"−03:00"
  },{
    "country":"America/Argentina/San_Luis",
    "timeZone":"−03:00"
  },{
    "country":"America/Argentina/Tucuman",
    "timeZone":"−03:00"
  },{
    "country":"America/Argentina/Ushuaia",
    "timeZone":"−03:00"
  },{
    "country":"America/Aruba",
    "timeZone":"−04:00"
  },{
    "country":"America/Asuncion",
    "timeZone":"−04:00"
  },{
    "country":"America/Atikokan",
    "timeZone":"−05:00"
  },{
    "country":"America/Atka",
    "timeZone":"−10:00"
  },{
    "country":"America/Bahia",
    "timeZone":"−03:00"
  },{
    "country":"America/Bahia_Banderas",
    "timeZone":"−06:00"
  },{
    "country":"America/Barbados",
    "timeZone":"−04:00"
  },{
    "country":"America/Belem",
    "timeZone":"−03:00"
  },{
    "country":"America/Belize",
    "timeZone":"−06:00"
  },{
    "country":"America/Blanc-Sablon",
    "timeZone":"−04:00"
  },{
    "country":"America/Boa_Vista",
    "timeZone":"−04:00"
  },{
    "country":"America/Bogota",
    "timeZone":"−05:00"
  },{
    "country":"America/Boise",
    "timeZone":"−07:00"
  },{
    "country":"America/Buenos_Aires",
    "timeZone":"−03:00"
  },{
    "country":"America/Cambridge_Bay",
    "timeZone":"−07:00"
  },{
    "country":"America/Campo_Grande",
    "timeZone":"−04:00"
  },{
    "country":"America/Cancun",
    "timeZone":"−05:00"
  },{
    "country":"America/Caracas",
    "timeZone":"−04:00"
  },{
    "country":"America/Catamarca",
    "timeZone":"−03:00"
  },{
    "country":"America/Cayenne",
    "timeZone":"−03:00"
  },{
    "country":"America/Cayman",
    "timeZone":"−05:00"
  },{
    "country":"America/Chicago",
    "timeZone":"−06:00"
  },{
    "country":"America/Chihuahua",
    "timeZone":"−07:00"
  },{
    "country":"America/Coral_Harbour",
    "timeZone":"−05:00"
  },{
    "country":"America/Cordoba",
    "timeZone":"−03:00"
  },{
    "country":"America/Costa_Rica",
    "timeZone":"−06:00"
  },{
    "country":"America/Creston",
    "timeZone":"−07:00"
  },{
    "country":"America/Cuiaba",
    "timeZone":"−04:00"
  },{
    "country":"America/Curacao",
    "timeZone":"−04:00"
  },{
    "country":"America/Danmarkshavn",
    "timeZone":"+00:00"
  },{
    "country":"America/Dawson",
    "timeZone":"−08:00"
  },{
    "country":"America/Dawson_Creek",
    "timeZone":"−07:00"
  },{
    "country":"America/Denver",
    "timeZone":"−07:00"
  },{
    "country":"America/Detroit",
    "timeZone":"−05:00"
  },{
    "country":"America/Dominica",
    "timeZone":"−04:00"
  },{
    "country":"America/Edmonton",
    "timeZone":"−07:00"
  },{
    "country":"America/Eirunepe",
    "timeZone":"−05:00"
  },{
    "country":"America/El_Salvador",
    "timeZone":"−06:00"
  },{
    "country":"America/Ensenada",
    "timeZone":"−08:00"
  },{
    "country":"America/Fort_Nelson",
    "timeZone":"−07:00"
  },{
    "country":"America/Fort_Wayne",
    "timeZone":"−05:00"
  },{
    "country":"America/Fortaleza",
    "timeZone":"−03:00"
  },{
    "country":"America/Glace_Bay",
    "timeZone":"−04:00"
  },{
    "country":"America/Godthab",
    "timeZone":"−03:00"
  },{
    "country":"America/Goose_Bay",
    "timeZone":"−04:00"
  },{
    "country":"America/Grand_Turk",
    "timeZone":"−04:00"
  },{
    "country":"America/Grenada",
    "timeZone":"−04:00"
  },{
    "country":"America/Guadeloupe",
    "timeZone":"−04:00"
  },{
    "country":"America/Guatemala",
    "timeZone":"−06:00"
  },{
    "country":"America/Guayaquil",
    "timeZone":"−05:00"
  },{
    "country":"America/Guyana",
    "timeZone":"−04:00"
  },{
    "country":"America/Halifax",
    "timeZone":"−04:00"
  },{
    "country":"America/Havana",
    "timeZone":"−05:00"
  },{
    "country":"America/Hermosillo",
    "timeZone":"−07:00"
  },{
    "country":"America/Indiana/Indianapolis",
    "timeZone":"−05:00"
  },{
    "country":"America/Indiana/Knox",
    "timeZone":"−06:00"
  },{
    "country":"America/Indiana/Marengo",
    "timeZone":"−05:00"
  },{
    "country":"America/Indiana/Petersburg",
    "timeZone":"−05:00"
  },{
    "country":"America/Indiana/Tell_City",
    "timeZone":"−06:00"
  },{
    "country":"America/Indiana/Vevay",
    "timeZone":"−05:00"
  },{
    "country":"America/Indiana/Vincennes",
    "timeZone":"−05:00"
  },{
    "country":"America/Indiana/Winamac",
    "timeZone":"−05:00"
  },{
    "country":"America/Indianapolis",
    "timeZone":"−05:00"
  },{
    "country":"America/Inuvik",
    "timeZone":"−07:00"
  },{
    "country":"America/Iqaluit",
    "timeZone":"−05:00"
  },{
    "country":"America/Jamaica",
    "timeZone":"−05:00"
  },{
    "country":"America/Jujuy",
    "timeZone":"−03:00"
  },{
    "country":"America/Juneau",
    "timeZone":"−09:00"
  },{
    "country":"America/Kentucky/Louisville",
    "timeZone":"−05:00"
  },{
    "country":"America/Kentucky/Monticello",
    "timeZone":"−05:00"
  },{
    "country":"America/Knox_IN",
    "timeZone":"−06:00"
  },{
    "country":"America/Kralendijk",
    "timeZone":"−04:00"
  },{
    "country":"America/La_Paz",
    "timeZone":"−04:00"
  },{
    "country":"America/Lima",
    "timeZone":"−05:00"
  },{
    "country":"America/Los_Angeles",
    "timeZone":"−08:00"
  },{
    "country":"America/Louisville",
    "timeZone":"−05:00"
  },{
    "country":"America/Lower_Princes",
    "timeZone":"−04:00"
  },{
    "country":"America/Maceio",
    "timeZone":"−03:00"
  },{
    "country":"America/Managua",
    "timeZone":"−06:00"
  },{
    "country":"America/Manaus",
    "timeZone":"−04:00"
  },{
    "country":"America/Marigot",
    "timeZone":"−04:00"
  },{
    "country":"America/Martinique",
    "timeZone":"−04:00"
  },{
    "country":"America/Matamoros",
    "timeZone":"−06:00"
  },{
    "country":"America/Mazatlan",
    "timeZone":"−07:00"
  },{
    "country":"America/Mendoza",
    "timeZone":"−03:00"
  },{
    "country":"America/Menominee",
    "timeZone":"−06:00"
  },{
    "country":"America/Merida",
    "timeZone":"−06:00"
  },{
    "country":"America/Metlakatla",
    "timeZone":"−09:00"
  },{
    "country":"America/Mexico_City",
    "timeZone":"−06:00"
  },{
    "country":"America/Miquelon",
    "timeZone":"−03:00"
  },{
    "country":"America/Moncton",
    "timeZone":"−04:00"
  },{
    "country":"America/Monterrey",
    "timeZone":"−06:00"
  },{
    "country":"America/Montevideo",
    "timeZone":"−03:00"
  },{
    "country":"America/Montreal",
    "timeZone":"−05:00"
  },{
    "country":"America/Montserrat",
    "timeZone":"−04:00"
  },{
    "country":"America/Nassau",
    "timeZone":"−05:00"
  },{
    "country":"America/New_York",
    "timeZone":"−05:00"
  },{
    "country":"America/Nipigon",
    "timeZone":"−05:00"
  },{
    "country":"America/Nome",
    "timeZone":"−09:00"
  },{
    "country":"America/Noronha",
    "timeZone":"−02:00"
  },{
    "country":"America/North_Dakota/Beulah",
    "timeZone":"−06:00"
  },{
    "country":"America/North_Dakota/Center",
    "timeZone":"−06:00"
  },{
    "country":"America/North_Dakota/New_Salem",
    "timeZone":"−06:00"
  },{
    "country":"America/Ojinaga",
    "timeZone":"−07:00"
  },{
    "country":"America/Panama",
    "timeZone":"−05:00"
  },{
    "country":"America/Pangnirtung",
    "timeZone":"−05:00"
  },{
    "country":"America/Paramaribo",
    "timeZone":"−03:00"
  },{
    "country":"America/Phoenix",
    "timeZone":"−07:00"
  },{
    "country":"America/Port_of_Spain",
    "timeZone":"−04:00"
  },{
    "country":"America/Port-au-Prince",
    "timeZone":"−05:00"
  },{
    "country":"America/Porto_Acre",
    "timeZone":"−05:00"
  },{
    "country":"America/Porto_Velho",
    "timeZone":"−04:00"
  },{
    "country":"America/Puerto_Rico",
    "timeZone":"−04:00"
  },{
    "country":"America/Punta_Arenas",
    "timeZone":"−03:00"
  },{
    "country":"America/Rainy_River",
    "timeZone":"−06:00"
  },{
    "country":"America/Rankin_Inlet",
    "timeZone":"−06:00"
  },{
    "country":"America/Recife",
    "timeZone":"−03:00"
  },{
    "country":"America/Regina",
    "timeZone":"−06:00"
  },{
    "country":"America/Resolute",
    "timeZone":"−06:00"
  },{
    "country":"America/Rio_Branco",
    "timeZone":"−05:00"
  },{
    "country":"America/Rosario",
    "timeZone":"−03:00"
  },{
    "country":"America/Santa_Isabel",
    "timeZone":"−08:00"
  },{
    "country":"America/Santarem",
    "timeZone":"−03:00"
  },{
    "country":"America/Santiago",
    "timeZone":"−04:00"
  },{
    "country":"America/Santo_Domingo",
    "timeZone":"−04:00"
  },{
    "country":"America/Sao_Paulo",
    "timeZone":"−03:00"
  },{
    "country":"America/Scoresbysund",
    "timeZone":"−01:00"
  },{
    "country":"America/Shiprock",
    "timeZone":"−07:00"
  },{
    "country":"America/Sitka",
    "timeZone":"−09:00"
  },{
    "country":"America/St_Barthelemy",
    "timeZone":"−04:00"
  },{
    "country":"America/St_Johns",
    "timeZone":"−03:30"
  },{
    "country":"America/St_Kitts",
    "timeZone":"−04:00"
  },{
    "country":"America/St_Lucia",
    "timeZone":"−04:00"
  },{
    "country":"America/St_Thomas",
    "timeZone":"−04:00"
  },{
    "country":"America/St_Vincent",
    "timeZone":"−04:00"
  },{
    "country":"America/Swift_Current",
    "timeZone":"−06:00"
  },{
    "country":"America/Tegucigalpa",
    "timeZone":"−06:00"
  },{
    "country":"America/Thule",
    "timeZone":"−04:00"
  },{
    "country":"America/Thunder_Bay",
    "timeZone":"−05:00"
  },{
    "country":"America/Tijuana",
    "timeZone":"−08:00"
  },{
    "country":"America/Toronto",
    "timeZone":"−05:00"
  },{
    "country":"America/Tortola",
    "timeZone":"−04:00"
  },{
    "country":"America/Vancouver",
    "timeZone":"−08:00"
  },{
    "country":"America/Virgin",
    "timeZone":"−04:00"
  },{
    "country":"America/Whitehorse",
    "timeZone":"−08:00"
  },{
    "country":"America/Winnipeg",
    "timeZone":"−06:00"
  },{
    "country":"America/Yakutat",
    "timeZone":"−09:00"
  },{
    "country":"America/Yellowknife",
    "timeZone":"−07:00"
  },{
    "country":"Antarctica/Casey",
    "timeZone":"+11:00"
  },{
    "country":"Antarctica/Davis",
    "timeZone":"+07:00"
  },{
    "country":"Antarctica/DumontDUrville",
    "timeZone":"+10:00"
  },{
    "country":"Antarctica/Macquarie",
    "timeZone":"+11:00"
  },{
    "country":"Antarctica/Mawson",
    "timeZone":"+05:00"
  },{
    "country":"Antarctica/McMurdo",
    "timeZone":"+12:00"
  },{
    "country":"Antarctica/Palmer",
    "timeZone":"−03:00"
  },{
    "country":"Antarctica/Rothera",
    "timeZone":"−03:00"
  },{
    "country":"Antarctica/South_Pole",
    "timeZone":"+12:00"
  },{
    "country":"Antarctica/Syowa",
    "timeZone":"+03:00"
  },{
    "country":"Antarctica/Troll",
    "timeZone":"+00:00"
  },{
    "country":"Antarctica/Vostok",
    "timeZone":"+06:00"
  },{
    "country":"Arctic/Longyearbyen",
    "timeZone":"+01:00"
  },{
    "country":"Asia/Aden",
    "timeZone":"+03:00"
  },{
    "country":"Asia/Almaty",
    "timeZone":"+06:00"
  },{
    "country":"Asia/Amman",
    "timeZone":"+02:00"
  },{
    "country":"Asia/Anadyr",
    "timeZone":"+12:00"
  },{
    "country":"Asia/Aqtau",
    "timeZone":"+05:00"
  },{
    "country":"Asia/Aqtobe",
    "timeZone":"+05:00"
  },{
    "country":"Asia/Ashgabat",
    "timeZone":"+05:00"
  },{
    "country":"Asia/Ashkhabad",
    "timeZone":"+05:00"
  },{
    "country":"Asia/Atyrau",
    "timeZone":"+05:00"
  },{
    "country":"Asia/Baghdad",
    "timeZone":"+03:00"
  },{
    "country":"Asia/Bahrain",
    "timeZone":"+03:00"
  },{
    "country":"Asia/Baku",
    "timeZone":"+04:00"
  },{
    "country":"Asia/Bangkok",
    "timeZone":"+07:00"
  },{
    "country":"Asia/Barnaul",
    "timeZone":"+07:00"
  },{
    "country":"Asia/Beirut",
    "timeZone":"+02:00"
  },{
    "country":"Asia/Bishkek",
    "timeZone":"+06:00"
  },{
    "country":"Asia/Brunei",
    "timeZone":"+08:00"
  },{
    "country":"Asia/Calcutta",
    "timeZone":"+05:30"
  },{
    "country":"Asia/Chita",
    "timeZone":"+09:00"
  },{
    "country":"Asia/Choibalsan",
    "timeZone":"+08:00"
  },{
    "country":"Asia/Chongqing",
    "timeZone":"+08:00"
  },{
    "country":"Asia/Chungking",
    "timeZone":"+08:00"
  },{
    "country":"Asia/Colombo",
    "timeZone":"+05:30"
  },{
    "country":"Asia/Dacca",
    "timeZone":"+06:00"
  },{
    "country":"Asia/Damascus",
    "timeZone":"+02:00"
  },{
    "country":"Asia/Dhaka",
    "timeZone":"+06:00"
  },{
    "country":"Asia/Dili",
    "timeZone":"+09:00"
  },{
    "country":"Asia/Dubai",
    "timeZone":"+04:00"
  },{
    "country":"Asia/Dushanbe",
    "timeZone":"+05:00"
  },{
    "country":"Asia/Famagusta",
    "timeZone":"+02:00"
  },{
    "country":"Asia/Gaza",
    "timeZone":"+02:00"
  },{
    "country":"Asia/Harbin",
    "timeZone":"+08:00"
  },{
    "country":"Asia/Hebron",
    "timeZone":"+02:00"
  },{
    "country":"Asia/Ho_Chi_Minh",
    "timeZone":"+07:00"
  },{
    "country":"Asia/Hong_Kong",
    "timeZone":"+08:00"
  },{
    "country":"Asia/Hovd",
    "timeZone":"+07:00"
  },{
    "country":"Asia/Irkutsk",
    "timeZone":"+08:00"
  },{
    "country":"Asia/Istanbul",
    "timeZone":"+03:00"
  },{
    "country":"Asia/Jakarta",
    "timeZone":"+07:00"
  },{
    "country":"Asia/Jayapura",
    "timeZone":"+09:00"
  },{
    "country":"Asia/Jerusalem",
    "timeZone":"+02:00"
  },{
    "country":"Asia/Kabul",
    "timeZone":"+04:30"
  },{
    "country":"Asia/Kamchatka",
    "timeZone":"+12:00"
  },{
    "country":"Asia/Karachi",
    "timeZone":"+05:00"
  },{
    "country":"Asia/Kashgar",
    "timeZone":"+06:00"
  },{
    "country":"Asia/Kathmandu",
    "timeZone":"+05:45"
  },{
    "country":"Asia/Katmandu",
    "timeZone":"+05:45"
  },{
    "country":"Asia/Khandyga",
    "timeZone":"+09:00"
  },{
    "country":"Asia/Kolkata",
    "timeZone":"+05:30"
  },{
    "country":"Asia/Krasnoyarsk",
    "timeZone":"+07:00"
  },{
    "country":"Asia/Kuala_Lumpur",
    "timeZone":"+08:00"
  },{
    "country":"Asia/Kuching",
    "timeZone":"+08:00"
  },{
    "country":"Asia/Kuwait",
    "timeZone":"+03:00"
  },{
    "country":"Asia/Macao",
    "timeZone":"+08:00"
  },{
    "country":"Asia/Macau",
    "timeZone":"+08:00"
  },{
    "country":"Asia/Magadan",
    "timeZone":"+11:00"
  },{
    "country":"Asia/Makassar",
    "timeZone":"+08:00"
  },{
    "country":"Asia/Manila",
    "timeZone":"+08:00"
  },{
    "country":"Asia/Muscat",
    "timeZone":"+04:00"
  },{
    "country":"Asia/Novokuznetsk",
    "timeZone":"+07:00"
  },{
    "country":"Asia/Novosibirsk",
    "timeZone":"+07:00"
  },{
    "country":"Asia/Omsk",
    "timeZone":"+06:00"
  },{
    "country":"Asia/Oral",
    "timeZone":"+05:00"
  },{
    "country":"Asia/Phnom_Penh",
    "timeZone":"+07:00"
  },{
    "country":"Asia/Pontianak",
    "timeZone":"+07:00"
  },{
    "country":"Asia/Pyongyang",
    "timeZone":"+09:00"
  },{
    "country":"Asia/Qatar",
    "timeZone":"+03:00"
  },{
    "country":"Asia/Qyzylorda",
    "timeZone":"+06:00"
  },{
    "country":"Asia/Rangoon",
    "timeZone":"+06:30"
  },{
    "country":"Asia/Riyadh",
    "timeZone":"+03:00"
  },{
    "country":"Asia/Saigon",
    "timeZone":"+07:00"
  },{
    "country":"Asia/Sakhalin",
    "timeZone":"+11:00"
  },{
    "country":"Asia/Samarkand",
    "timeZone":"+05:00"
  },{
    "country":"Asia/Seoul",
    "timeZone":"+09:00"
  },{
    "country":"Asia/Shanghai",
    "timeZone":"+08:00"
  },{
    "country":"Asia/Singapore",
    "timeZone":"+08:00"
  },{
    "country":"Asia/Srednekolymsk",
    "timeZone":"+11:00"
  },{
    "country":"Asia/Taipei",
    "timeZone":"+08:00"
  },{
    "country":"Asia/Tashkent",
    "timeZone":"+05:00"
  },{
    "country":"Asia/Tbilisi",
    "timeZone":"+04:00"
  },{
    "country":"Asia/Tehran",
    "timeZone":"+03:30"
  },{
    "country":"Asia/Tel_Aviv",
    "timeZone":"+02:00"
  },{
    "country":"Asia/Thimbu",
    "timeZone":"+06:00"
  },{
    "country":"Asia/Thimphu",
    "timeZone":"+06:00"
  },{
    "country":"Asia/Tokyo",
    "timeZone":"+09:00"
  },{
    "country":"Asia/Tomsk",
    "timeZone":"+07:00"
  },{
    "country":"Asia/Ujung_Pandang",
    "timeZone":"+08:00"
  },{
    "country":"Asia/Ulaanbaatar",
    "timeZone":"+08:00"
  },{
    "country":"Asia/Ulan_Bator",
    "timeZone":"+08:00"
  },{
    "country":"Asia/Urumqi",
    "timeZone":"+06:00"
  },{
    "country":"Asia/Ust-Nera",
    "timeZone":"+10:00"
  },{
    "country":"Asia/Vientiane",
    "timeZone":"+07:00"
  },{
    "country":"Asia/Vladivostok",
    "timeZone":"+10:00"
  },{
    "country":"Asia/Yakutsk",
    "timeZone":"+09:00"
  },{
    "country":"Asia/Yangon",
    "timeZone":"+06:30"
  },{
    "country":"Asia/Yekaterinburg",
    "timeZone":"+05:00"
  },{
    "country":"Asia/Yerevan",
    "timeZone":"+04:00"
  },{
    "country":"Atlantic/Azores",
    "timeZone":"−01:00"
  },{
    "country":"Atlantic/Bermuda",
    "timeZone":"−04:00"
  },{
    "country":"Atlantic/Canary",
    "timeZone":"+00:00"
  },{
    "country":"Atlantic/Cape_Verde",
    "timeZone":"−01:00"
  },{
    "country":"Atlantic/Faeroe",
    "timeZone":"+00:00"
  },{
    "country":"Atlantic/Faroe",
    "timeZone":"+00:00"
  },{
    "country":"Atlantic/Jan_Mayen",
    "timeZone":"+01:00"
  },{
    "country":"Atlantic/Madeira",
    "timeZone":"+00:00"
  },{
    "country":"Atlantic/Reykjavik",
    "timeZone":"+00:00"
  },{
    "country":"Atlantic/South_Georgia",
    "timeZone":"−02:00"
  },{
    "country":"Atlantic/St_Helena",
    "timeZone":"+00:00"
  },{
    "country":"Atlantic/Stanley",
    "timeZone":"−03:00"
  },{
    "country":"Australia/ACT",
    "timeZone":"+10:00"
  },{
    "country":"Australia/Adelaide",
    "timeZone":"+09:30"
  },{
    "country":"Australia/Brisbane",
    "timeZone":"+10:00"
  },{
    "country":"Australia/Broken_Hill",
    "timeZone":"+09:30"
  },{
    "country":"Australia/Canberra",
    "timeZone":"+10:00"
  },{
    "country":"Australia/Currie",
    "timeZone":"+10:00"
  },{
    "country":"Australia/Darwin",
    "timeZone":"+09:30"
  },{
    "country":"Australia/Eucla",
    "timeZone":"+08:45"
  },{
    "country":"Australia/Hobart",
    "timeZone":"+10:00"
  },{
    "country":"Australia/LHI",
    "timeZone":"+10:30"
  },{
    "country":"Australia/Lindeman",
    "timeZone":"+10:00"
  },{
    "country":"Australia/Lord_Howe",
    "timeZone":"+10:30"
  },{
    "country":"Australia/Melbourne",
    "timeZone":"+10:00"
  },{
    "country":"Australia/North",
    "timeZone":"+09:30"
  },{
    "country":"Australia/NSW",
    "timeZone":"+10:00"
  },{
    "country":"Australia/Perth",
    "timeZone":"+08:00"
  },{
    "country":"Australia/Queensland",
    "timeZone":"+10:00"
  },{
    "country":"Australia/South",
    "timeZone":"+09:30"
  },{
    "country":"Australia/Sydney",
    "timeZone":"+10:00"
  },{
    "country":"Australia/Tasmania",
    "timeZone":"+10:00"
  },{
    "country":"Australia/Victoria",
    "timeZone":"+10:00"
  },{
    "country":"Australia/West",
    "timeZone":"+08:00"
  },{
    "country":"Australia/Yancowinna",
    "timeZone":"+09:30"
  },{
    "country":"Brazil/Acre",
    "timeZone":"−05:00"
  },{
    "country":"Brazil/DeNoronha",
    "timeZone":"−02:00"
  },{
    "country":"Brazil/East",
    "timeZone":"−03:00"
  },{
    "country":"Brazil/West",
    "timeZone":"−04:00"
  },{
    "country":"Canada/Atlantic",
    "timeZone":"−04:00"
  },{
    "country":"Canada/Central",
    "timeZone":"−06:00"
  },{
    "country":"Canada/Eastern",
    "timeZone":"−05:00"
  },{
    "country":"Canada/Mountain",
    "timeZone":"−07:00"
  },{
    "country":"Canada/Newfoundland",
    "timeZone":"−03:30"
  },{
    "country":"Canada/Pacific",
    "timeZone":"−08:00"
  },{
    "country":"Canada/Saskatchewan",
    "timeZone":"−06:00"
  },{
    "country":"Canada/Yukon",
    "timeZone":"−08:00"
  },{
    "country":"CET",
    "timeZone":"+01:00"
  },{
    "country":"Chile/Continental",
    "timeZone":"−04:00"
  },{
    "country":"Chile/EasterIsland",
    "timeZone":"−06:00"
  },{
    "country":"CST6CDT",
    "timeZone":"−06:00"
  },{
    "country":"Cuba",
    "timeZone":"−05:00"
  },{
    "country":"EET",
    "timeZone":"+02:00"
  },{
    "country":"Egypt",
    "timeZone":"+02:00"
  },{
    "country":"Eire",
    "timeZone":"+00:00"
  },{
    "country":"EST",
    "timeZone":"−05:00"
  },{
    "country":"EST5EDT",
    "timeZone":"−05:00"
  },{
    "country":"Etc/GMT",
    "timeZone":"+00:00"
  },{
    "country":"Etc/GMT+0",
    "timeZone":"+00:00"
  },{
    "country":"Etc/GMT+1",
    "timeZone":"−01:00"
  },{
    "country":"Etc/GMT+10",
    "timeZone":"−10:00"
  },{
    "country":"Etc/GMT+11",
    "timeZone":"−11:00"
  },{
    "country":"Etc/GMT+12",
    "timeZone":"−12:00"
  },{
    "country":"Etc/GMT+2",
    "timeZone":"−02:00"
  },{
    "country":"Etc/GMT+3",
    "timeZone":"−03:00"
  },{
    "country":"Etc/GMT+4",
    "timeZone":"−04:00"
  },{
    "country":"Etc/GMT+5",
    "timeZone":"−05:00"
  },{
    "country":"Etc/GMT+6",
    "timeZone":"−06:00"
  },{
    "country":"Etc/GMT+7",
    "timeZone":"−07:00"
  },{
    "country":"Etc/GMT+8",
    "timeZone":"−08:00"
  },{
    "country":"Etc/GMT+9",
    "timeZone":"−09:00"
  },{
    "country":"Etc/GMT0",
    "timeZone":"+00:00"
  },{
    "country":"Etc/GMT-0",
    "timeZone":"+00:00"
  },{
    "country":"Etc/GMT-1",
    "timeZone":"+01:00"
  },{
    "country":"Etc/GMT-10",
    "timeZone":"+10:00"
  },{
    "country":"Etc/GMT-11",
    "timeZone":"+11:00"
  },{
    "country":"Etc/GMT-12",
    "timeZone":"+12:00"
  },{
    "country":"Etc/GMT-13",
    "timeZone":"+13:00"
  },{
    "country":"Etc/GMT-14",
    "timeZone":"+14:00"
  },{
    "country":"Etc/GMT-2",
    "timeZone":"+02:00"
  },{
    "country":"Etc/GMT-3",
    "timeZone":"+03:00"
  },{
    "country":"Etc/GMT-4",
    "timeZone":"+04:00"
  },{
    "country":"Etc/GMT-5",
    "timeZone":"+05:00"
  },{
    "country":"Etc/GMT-6",
    "timeZone":"+06:00"
  },{
    "country":"Etc/GMT-7",
    "timeZone":"+07:00"
  },{
    "country":"Etc/GMT-8",
    "timeZone":"+08:00"
  },{
    "country":"Etc/GMT-9",
    "timeZone":"+09:00"
  },{
    "country":"Etc/Greenwich",
    "timeZone":"+00:00"
  },{
    "country":"Etc/UCT",
    "timeZone":"+00:00"
  },{
    "country":"Etc/Universal",
    "timeZone":"+00:00"
  },{
    "country":"Etc/UTC",
    "timeZone":"+00:00"
  },{
    "country":"Etc/Zulu",
    "timeZone":"+00:00"
  },{
    "country":"Europe/Amsterdam",
    "timeZone":"+01:00"
  },{
    "country":"Europe/Andorra",
    "timeZone":"+01:00"
  },{
    "country":"Europe/Astrakhan",
    "timeZone":"+04:00"
  },{
    "country":"Europe/Athens",
    "timeZone":"+02:00"
  },{
    "country":"Europe/Belfast",
    "timeZone":"+00:00"
  },{
    "country":"Europe/Belgrade",
    "timeZone":"+01:00"
  },{
    "country":"Europe/Berlin",
    "timeZone":"+01:00"
  },{
    "country":"Europe/Bratislava",
    "timeZone":"+01:00"
  },{
    "country":"Europe/Brussels",
    "timeZone":"+01:00"
  },{
    "country":"Europe/Bucharest",
    "timeZone":"+02:00"
  },{
    "country":"Europe/Budapest",
    "timeZone":"+01:00"
  },{
    "country":"Europe/Busingen",
    "timeZone":"+01:00"
  },{
    "country":"Europe/Chisinau",
    "timeZone":"+02:00"
  },{
    "country":"Europe/Copenhagen",
    "timeZone":"+01:00"
  },{
    "country":"Europe/Dublin",
    "timeZone":"+00:00"
  },{
    "country":"Europe/Gibraltar",
    "timeZone":"+01:00"
  },{
    "country":"Europe/Guernsey",
    "timeZone":"+00:00"
  },{
    "country":"Europe/Helsinki",
    "timeZone":"+02:00"
  },{
    "country":"Europe/Isle_of_Man",
    "timeZone":"+00:00"
  },{
    "country":"Europe/Istanbul",
    "timeZone":"+03:00"
  },{
    "country":"Europe/Jersey",
    "timeZone":"+00:00"
  },{
    "country":"Europe/Kaliningrad",
    "timeZone":"+02:00"
  },{
    "country":"Europe/Kyiv",
    "timeZone":"+02:00"
  },{
    "country":"Europe/Kirov",
    "timeZone":"+03:00"
  },{
    "country":"Europe/Lisbon",
    "timeZone":"+00:00"
  },{
    "country":"Europe/Ljubljana",
    "timeZone":"+01:00"
  },{
    "country":"Europe/London",
    "timeZone":"+00:00"
  },{
    "country":"Europe/Luxembourg",
    "timeZone":"+01:00"
  },{
    "country":"Europe/Madrid",
    "timeZone":"+01:00"
  },{
    "country":"Europe/Malta",
    "timeZone":"+01:00"
  },{
    "country":"Europe/Mariehamn",
    "timeZone":"+02:00"
  },{
    "country":"Europe/Minsk",
    "timeZone":"+03:00"
  },{
    "country":"Europe/Monaco",
    "timeZone":"+01:00"
  },{
    "country":"Europe/Moscow",
    "timeZone":"+03:00"
  },{
    "country":"Europe/Nicosia",
    "timeZone":"+02:00"
  },{
    "country":"Europe/Oslo",
    "timeZone":"+01:00"
  },{
    "country":"Europe/Paris",
    "timeZone":"+01:00"
  },{
    "country":"Europe/Podgorica",
    "timeZone":"+01:00"
  },{
    "country":"Europe/Prague",
    "timeZone":"+01:00"
  },{
    "country":"Europe/Riga",
    "timeZone":"+02:00"
  },{
    "country":"Europe/Rome",
    "timeZone":"+01:00"
  },{
    "country":"Europe/Samara",
    "timeZone":"+04:00"
  },{
    "country":"Europe/San_Marino",
    "timeZone":"+01:00"
  },{
    "country":"Europe/Sarajevo",
    "timeZone":"+01:00"
  },{
    "country":"Europe/Saratov",
    "timeZone":"+04:00"
  },{
    "country":"Europe/Simferopol",
    "timeZone":"+03:00"
  },{
    "country":"Europe/Skopje",
    "timeZone":"+01:00"
  },{
    "country":"Europe/Sofia",
    "timeZone":"+02:00"
  },{
    "country":"Europe/Stockholm",
    "timeZone":"+01:00"
  },{
    "country":"Europe/Tallinn",
    "timeZone":"+02:00"
  },{
    "country":"Europe/Tirane",
    "timeZone":"+01:00"
  },{
    "country":"Europe/Tiraspol",
    "timeZone":"+02:00"
  },{
    "country":"Europe/Ulyanovsk",
    "timeZone":"+04:00"
  },{
    "country":"Europe/Uzhgorod",
    "timeZone":"+02:00"
  },{
    "country":"Europe/Vaduz",
    "timeZone":"+01:00"
  },{
    "country":"Europe/Vatican",
    "timeZone":"+01:00"
  },{
    "country":"Europe/Vienna",
    "timeZone":"+01:00"
  },{
    "country":"Europe/Vilnius",
    "timeZone":"+02:00"
  },{
    "country":"Europe/Volgograd",
    "timeZone":"+04:00"
  },{
    "country":"Europe/Warsaw",
    "timeZone":"+01:00"
  },{
    "country":"Europe/Zagreb",
    "timeZone":"+01:00"
  },{
    "country":"Europe/Zaporozhye",
    "timeZone":"+02:00"
  },{
    "country":"Europe/Zurich",
    "timeZone":"+01:00"
  },{
    "country":"GB",
    "timeZone":"+00:00"
  },{
    "country":"GB-Eire",
    "timeZone":"+00:00"
  },{
    "country":"GMT",
    "timeZone":"+00:00"
  },{
    "country":"GMT+0",
    "timeZone":"+00:00"
  },{
    "country":"GMT0",
    "timeZone":"+00:00"
  },{
    "country":"GMT−0",
    "timeZone":"+00:00"
  },{
    "country":"Greenwich",
    "timeZone":"+00:00"
  },{
    "country":"Hongkong",
    "timeZone":"+08:00"
  },{
    "country":"HST",
    "timeZone":"−10:00"
  },{
    "country":"Iceland",
    "timeZone":"+00:00"
  },{
    "country":"Indian/Antananarivo",
    "timeZone":"+03:00"
  },{
    "country":"Indian/Chagos",
    "timeZone":"+06:00"
  },{
    "country":"Indian/Christmas",
    "timeZone":"+07:00"
  },{
    "country":"Indian/Cocos",
    "timeZone":"+06:30"
  },{
    "country":"Indian/Comoro",
    "timeZone":"+03:00"
  },{
    "country":"Indian/Kerguelen",
    "timeZone":"+05:00"
  },{
    "country":"Indian/Mahe",
    "timeZone":"+04:00"
  },{
    "country":"Indian/Maldives",
    "timeZone":"+05:00"
  },{
    "country":"Indian/Mauritius",
    "timeZone":"+04:00"
  },{
    "country":"Indian/Mayotte",
    "timeZone":"+03:00"
  },{
    "country":"Indian/Reunion",
    "timeZone":"+04:00"
  },{
    "country":"Iran",
    "timeZone":"+03:30"
  },{
    "country":"Israel",
    "timeZone":"+02:00"
  },{
    "country":"Jamaica",
    "timeZone":"−05:00"
  },{
    "country":"Japan",
    "timeZone":"+09:00"
  },{
    "country":"Kwajalein",
    "timeZone":"+12:00"
  },{
    "country":"Libya",
    "timeZone":"+02:00"
  },{
    "country":"MET",
    "timeZone":"+01:00"
  },{
    "country":"Mexico/BajaNorte",
    "timeZone":"−08:00"
  },{
    "country":"Mexico/BajaSur",
    "timeZone":"−07:00"
  },{
    "country":"Mexico/General",
    "timeZone":"−06:00"
  },{
    "country":"MST",
    "timeZone":"−07:00"
  },{
    "country":"MST7MDT",
    "timeZone":"−07:00"
  },{
    "country":"Navajo",
    "timeZone":"−07:00"
  },{
    "country":"NZ",
    "timeZone":"+12:00"
  },{
    "country":"NZ-CHAT",
    "timeZone":"+12:45"
  },{
    "country":"Pacific/Apia",
    "timeZone":"+13:00"
  },{
    "country":"Pacific/Auckland",
    "timeZone":"+12:00"
  },{
    "country":"Pacific/Bougainville",
    "timeZone":"+11:00"
  },{
    "country":"Pacific/Chatham",
    "timeZone":"+12:45"
  },{
    "country":"Pacific/Chuuk",
    "timeZone":"+10:00"
  },{
    "country":"Pacific/Easter",
    "timeZone":"−06:00"
  },{
    "country":"Pacific/Efate",
    "timeZone":"+11:00"
  },{
    "country":"Pacific/Enderbury",
    "timeZone":"+13:00"
  },{
    "country":"Pacific/Fakaofo",
    "timeZone":"+13:00"
  },{
    "country":"Pacific/Fiji",
    "timeZone":"+12:00"
  },{
    "country":"Pacific/Funafuti",
    "timeZone":"+12:00"
  },{
    "country":"Pacific/Galapagos",
    "timeZone":"−06:00"
  },{
    "country":"Pacific/Gambier",
    "timeZone":"−09:00"
  },{
    "country":"Pacific/Guadalcanal",
    "timeZone":"+11:00"
  },{
    "country":"Pacific/Guam",
    "timeZone":"+10:00"
  },{
    "country":"Pacific/Honolulu",
    "timeZone":"−10:00"
  },{
    "country":"Pacific/Johnston",
    "timeZone":"−10:00"
  },{
    "country":"Pacific/Kiritimati",
    "timeZone":"+14:00"
  },{
    "country":"Pacific/Kosrae",
    "timeZone":"+11:00"
  },{
    "country":"Pacific/Kwajalein",
    "timeZone":"+12:00"
  },{
    "country":"Pacific/Majuro",
    "timeZone":"+12:00"
  },{
    "country":"Pacific/Marquesas",
    "timeZone":"−09:30"
  },{
    "country":"Pacific/Midway",
    "timeZone":"−11:00"
  },{
    "country":"Pacific/Nauru",
    "timeZone":"+12:00"
  },{
    "country":"Pacific/Niue",
    "timeZone":"−11:00"
  },{
    "country":"Pacific/Norfolk",
    "timeZone":"+11:00"
  },{
    "country":"Pacific/Noumea",
    "timeZone":"+11:00"
  },{
    "country":"Pacific/Pago_Pago",
    "timeZone":"−11:00"
  },{
    "country":"Pacific/Palau",
    "timeZone":"+09:00"
  },{
    "country":"Pacific/Pitcairn",
    "timeZone":"−08:00"
  },{
    "country":"Pacific/Pohnpei",
    "timeZone":"+11:00"
  },{
    "country":"Pacific/Ponape",
    "timeZone":"+11:00"
  },{
    "country":"Pacific/Port_Moresby",
    "timeZone":"+10:00"
  },{
    "country":"Pacific/Rarotonga",
    "timeZone":"−10:00"
  },{
    "country":"Pacific/Saipan",
    "timeZone":"+10:00"
  },{
    "country":"Pacific/Samoa",
    "timeZone":"−11:00"
  },{
    "country":"Pacific/Tahiti",
    "timeZone":"−10:00"
  },{
    "country":"Pacific/Tarawa",
    "timeZone":"+12:00"
  },{
    "country":"Pacific/Tongatapu",
    "timeZone":"+13:00"
  },{
    "country":"Pacific/Truk",
    "timeZone":"+10:00"
  },{
    "country":"Pacific/Wake",
    "timeZone":"+12:00"
  },{
    "country":"Pacific/Wallis",
    "timeZone":"+12:00"
  },{
    "country":"Pacific/Yap",
    "timeZone":"+10:00"
  },{
    "country":"Poland",
    "timeZone":"+01:00"
  },{
    "country":"Portugal",
    "timeZone":"+00:00"
  },{
    "country":"PRC",
    "timeZone":"+08:00"
  },{
    "country":"PST8PDT",
    "timeZone":"−08:00"
  },{
    "country":"ROC",
    "timeZone":"+08:00"
  },{
    "country":"ROK",
    "timeZone":"+09:00"
  },{
    "country":"Singapore",
    "timeZone":"+08:00"
  },{
    "country":"Turkey",
    "timeZone":"+03:00"
  },{
    "country":"UCT",
    "timeZone":"+00:00"
  },{
    "country":"Universal",
    "timeZone":"+00:00"
  },{
    "country":"US/Alaska",
    "timeZone":"−09:00"
  },{
    "country":"US/Aleutian",
    "timeZone":"−10:00"
  },{
    "country":"US/Arizona",
    "timeZone":"−07:00"
  },{
    "country":"US/Central",
    "timeZone":"−06:00"
  },{
    "country":"US/Eastern",
    "timeZone":"−05:00"
  },{
    "country":"US/East-Indiana",
    "timeZone":"−05:00"
  },{
    "country":"US/Hawaii",
    "timeZone":"−10:00"
  },{
    "country":"US/Indiana-Starke",
    "timeZone":"−06:00"
  },{
    "country":"US/Michigan",
    "timeZone":"−05:00"
  },{
    "country":"US/Mountain",
    "timeZone":"−07:00"
  },{
    "country":"US/Pacific",
    "timeZone":"−08:00"
  },{
    "country":"US/Pacific-New",
    "timeZone":"−08:00"
  },{
    "country":"US/Samoa",
    "timeZone":"−11:00"
  },{
    "country":"UTC",
    "timeZone":"+00:00"
  },{
    "country":"WET",
    "timeZone":"+00:00"
  },{
    "country":"W-SU",
    "timeZone":"+03:00"
  },{
    "country":"Zulu",
    "timeZone":"+00:00"
  }];

export class TimeZone {
    key: string;
    name: string;
    disabled: boolean;

    constructor(key, name, disabled = false) {
        this.key = key;
        this.name = name;
        this.disabled = disabled;
    }

    static getListTimeZone(): TimeZone[] {
        return listTimeZone.map(x => new TimeZone(x['country'], x['timeZone'], Boolean(x['disabled'])));
    }
}