export const ApiType = {
    CREATED_ADDRESSES: 'CREATED_ADDRESSES',
    CREATED_DEPOSITS: 'CREATED_DEPOSITS',
    READ_ADDRESSES: 'READ_ADDRESSES',
    READ_DEPOSITS: 'READ_DEPOSITS',
    READ_TRANSACTIONS: 'READ_TRANSACTIONS',
    SEND_TRANSACTIONS: 'SEND_TRANSACTIONS',
    USER_MAIL: 'USER_MAIL',
    USER_READ: 'USER_READ',
};